#! /usr/bin/env python3
from pylab import *

pjs = [1,3,4,5,6,7,8,9,12]
with open('data/mwr_global_average.txt', 'w') as file:
    file.write('# Generated by %s \n' % __file__.split('/')[-1])
    file.write('# Description:\n')
    file.write('#   Global averaged MWR observation (weighted by surface area)\n')
    file.write('# Parameters:\n')
    file.write('#   - epsilon_Tb (K) = 5.\n')
    file.write('#   - epsilon_Ld (%) = 0.5\n')
    file.write('# Using:\n')
    for i in range(1,7):
        file.write('#  ch%d_gfilter.txt\n' % i)
    file.write('\n# Nadir brightness temperature (K)\n')
    for i in range(len(pjs)):
        file.write('# PJ%d     ' % pjs[i])
    file.write('\n')
    for mwr_channel in range(1,7):
        data = genfromtxt('data/ch%d_gfilter.txt' % mwr_channel)
        nrows, ncols = data.shape
        data = data.reshape(4, nrows//4, ncols)
        tb = data[0,:,1:]
        eps_tb = data[1,:,1:]
        eps_ld = data[3,:,1:]
        lat = data[0,:,0]
        nlat, npj = tb.shape

        tb_avg2 = 0
        for i in range(npj):
            ix = (abs(eps_tb[:,i]) < 5.) & (abs(eps_ld[:,i]) < 0.5)
            #ix = (abs(eps_tb[:,i]) < 5.) & (abs(eps_ld[:,i]) < 0.5) & ((lat < 20.) & (lat > -20.))
            tb1 = tb[ix,i]
            lat1 = lat[ix]/180.*pi
            tb_area = (tb1[1:] + tb1[:-1])/2.
            area = sin(lat1[1:]) - sin(lat1[:-1])
            tb_avg = dot(tb_area, area)/sum(area)
            tb_avg2 += tb_avg
            file.write('%-10.4f' % tb_avg)
        file.write('\n')
    file.write('\n# Limb darkening (%)\n')
    for mwr_channel in range(1,7):
        data = genfromtxt('data/ch%d_gfilter.txt' % mwr_channel)
        nrows, ncols = data.shape
        data = data.reshape(4, nrows//4, ncols)
        ld = data[2,:,1:]
        eps_tb = data[1,:,1:]
        eps_ld = data[3,:,1:]
        lat = data[0,:,0]
        nlat, npj = ld.shape

        for i in range(npj):
            ix = (abs(eps_tb[:,i]) < 5.) & (abs(eps_ld[:,i]) < 0.5)
            ld1 = ld[ix,i]
            lat1 = lat[ix]/180.*pi
            ld_area = (ld1[1:] + ld1[:-1])/2.
            area = sin(lat1[1:]) - sin(lat1[:-1])
            ld_avg = dot(ld_area, area)/sum(area)
            file.write('%-10.4f' % ld_avg)
        file.write('\n')
