#! /usr/bin/env python3
from pylab import *

data = genfromtxt('data/mwr_global_average.txt')
nrows, ncols = data.shape
data = data.reshape((2, nrows//2, ncols))
tb0 = mean(data[0,:,:], axis = 1)
tb0_std = std(data[0,:,:], axis = 1)
ld0 = mean(data[1,:,:], axis = 1)
ld0_std = std(data[1,:,:], axis = 1)

with open('data/mwr_zonal_average.txt', 'w') as file:
  file.write('# Generated by %s \n' % __file__.split('/')[-1])
  file.write('# Description:\n')
  file.write('#   MWR zonal average\n')
  file.write('# Using:\n')
  file.write('#  mwr_global_average.txt\n')
  file.write('#  mwr_zonal_anomaly.txt\n\n')
  file.write('# Global mean Tb (K), std (K)\n')
  for i in range(len(tb0)):
    file.write('%10.4f %10.4f\n' % (tb0[i], tb0_std[i]))
  file.write('# Global mean Ld (%), std (%)\n')
  for i in range(len(tb0)):
    file.write('%10.4f %10.4f\n' % (ld0[i], ld0_std[i]))

data = genfromtxt('data/mwr_zonal_anomaly.txt')
nrows, ncols = data.shape
data = data.reshape(6, 2, nrows//12, ncols)
tb1 = data[:,0,:,1:]
ld1 = data[:,1,:,1:]
lat = data[0,0,:,0]
nfreq, nlat, npj = tb1.shape

# 3-point smoothing for tb1 and ld1
#tb1[:,1:-1,:] = (tb1[:,1:-1,:] + tb1[:,2:,:] + tb1[:,:-2,:])/3.
#ld1[:,1:-1,:] = (ld1[:,1:-1,:] + ld1[:,2:,:] + ld1[:,:-2,:])/3.

freqs = [0.6, 1.25, 2.6, 5.2, 10., 22.]
tb1_avg = zeros(nlat)
tb1_std = zeros(nlat)

# Zonal Tb
with open('data/mwr_zonal_average.txt', 'a') as file:
  for i in range(nfreq):
    file.write('# CH%d zonally averaged Tb anomaly (K), std (K)\n' % (i+1))
    for j in range(nlat):
      ix = abs(tb1[i,j,:]) > 0.
      tb1_avg[j] = mean(tb1[i,j,ix])
      tb1_std[j] = std(tb1[i,j,ix], ddof = 1)
    # 3-point smoothing for tb1
    tb1_avg[1:-1] = (tb1_avg[1:-1] + tb1_avg[2:] + tb1_avg[:-2])/3.
    tb1_std[1:-1] = sqrt((tb1_std[1:-1]**2 + tb1_std[2:]**2 + tb1_std[:-2]**2)/3.)
    for j in range(nlat):
      file.write('%10.4f %10.4f %10.4f\n' % (lat[j], tb1_avg[j], tb1_std[j]))

# Zonal Ld
ld1_avg = zeros(nlat)
ld1_std = zeros(nlat)
with open('data/mwr_zonal_average.txt', 'a') as file:
  for i in range(nfreq):
    file.write('# CH%d zonally '%(i+1) + 'averaged Ld anomaly (%), std (%)\n')
    for j in range(nlat):
      ix = abs(ld1[i,j,:]) > 0.
      ld1_avg[j] = mean(ld1[i,j,ix])
      ld1_std[j] = std(ld1[i,j,ix], ddof = 1)
    # 3-point smoothing for ld1
    ld1_avg[1:-1] = (ld1_avg[1:-1] + ld1_avg[2:] + ld1_avg[:-2])/3.
    ld1_std[1:-1] = sqrt((ld1_std[1:-1]**2 + ld1_std[2:]**2 + ld1_std[:-2]**2)/3.)
    for j in range(nlat):
      file.write('%10.4f %10.4f %10.4f\n' % (lat[j], ld1_avg[j], ld1_std[j]))
