#! /usr/bin/env python3
from pylab import *
from scipy.interpolate import interp1d

data = genfromtxt('data/mwr_global_average.txt')
nrows, ncols = data.shape
data = data.reshape((2, nrows//2, ncols))
tb0 = mean(data[0,:,:], axis = 1)
ld0 = mean(data[1,:,:], axis = 1)

with open('data/mwr_zonal_anomaly.txt', 'w') as file:
    file.write('# Generated by %s \n' % __file__.split('/')[-1])
    file.write('# Description:\n')
    file.write('#   MWR zonal anomaly\n')
    file.write('# Parameters:\n')
    file.write('#   - epsilon_Tb (K) = 5.\n')
    file.write('#   - epsilon_Ld (%) = 0.5\n')
    file.write('#   - Tb0 (K) = \n#  ')
    for x in tb0:
        file.write('%-10.2f' % x)
    file.write('\n#   - Ld0 (%) = \n#  ')
    for x in ld0:
        file.write('%-10.2f' % x)
    file.write('\n# Using:\n')
    file.write('#  mwr_global_average.txt\n')
    for i in range(1,7):
        file.write('#  ch%d_gfilter.txt\n' % i)
    for mwr_channel in range(1,7):
        data = genfromtxt('data/ch%d_gfilter.txt' % mwr_channel)
        nrows, ncols = data.shape
        data = data.reshape(4, nrows//4, ncols)
        lat = data[0,:,0]
        tb = data[0,:,:]
        ld = data[2,:,:]
        eps_tb = data[1,:,:]
        eps_ld = data[3,:,:]
        #data[0,:,1:] -= tb0[mwr_channel-1]
        #data[2,:,1:] -= ld0[mwr_channel-1]
        file.write('# CH%d Tb anomaly (K)\n' % mwr_channel)
        for i in range(len(lat)):
            file.write('%10.4f' % lat[i])
            for j in range(1,ncols):
                ix = (abs(eps_tb[:,j]) < 5.) & (abs(eps_ld[:,j]) < 0.5)
                tb_func = interp1d(lat[ix], tb[ix,j] - tb0[mwr_channel-1],
                        fill_value = 0., bounds_error = False)
                file.write('%10.4f' % tb_func(lat[i]))
                #if (abs(eps_tb[i,j]) < 5.) and (abs(eps_ld[i,j]) < 0.5):
                #  file.write('%10.4f' % (tb[i,j] - tb0[mwr_channel-1],))
                #else:
                #  file.write('%10.4f' % 0.)
            file.write('\n')
        file.write('# CH%d Ld anomaly' % mwr_channel + ' (%)\n')
        for i in range(len(lat)):
            file.write('%10.4f' % lat[i])
            for j in range(1,ncols):
                ix = (abs(eps_tb[:,j]) < 5.) & (abs(eps_ld[:,j]) < 0.5)
                ld_func = interp1d(lat[ix], ld[ix,j] - ld0[mwr_channel-1],
                        fill_value = 0., bounds_error = False)
                file.write('%10.4f' % ld_func(lat[i]))
            file.write('\n')
